/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conga.ai.app;

import conga.ai.list.LinkedList;

import static conga.ai.utilities.StringUtils.join;
import static conga.ai.utilities.StringUtils.split;
import static conga.ai.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
